### PR TITLE
Implement naive S1 Z correction

### PR DESCRIPTION
**Pull request by cfuselli**
We add here a naive S1 correction based on Z coordinate. Kind of a placeholder for a better and more precise correction.  

@acolijn provided the details.

### CODE REVIEW

**Comment by tobiasdenhollander** [comment]
tpcdrawing
Veerry nitpicky, but should the lowest z value not be 50.5mm to account for the 1.5mm meshes?

**Comment by cfuselli** [comment]
@tobiasdenhollander probably right, but because AP tuned it like this and this is a placeholder anyway, maybe let's keep it like this for now?

**Comment by cfuselli** [comment]
@tobiasdenhollander apparently it is 52 as @acolijn says

**Comment by tobiasdenhollander** [comment]
oh wait, maybe I read the drawing wrong. All good by me!

**Review by tobiasdenhollander — APPROVED** [review]
looks good

**Pull request merged**
